version: "3"

services:
  api_gateway:
    image: spread-hub:latest
    ports:
      - 4000:4000      
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
    networks:
      - web

networks:
  web:
    driver: overlay
